from set_uptools import find_packages, set_up


with open("README.md") as f:
    long_description = f.read()

INSTALL_REQUIRES = [
    "loguru==0.7.2",
    "tqdm==4.66.1",
    "matplotlib==3.8.0",
    "numpy==1.23.0",
    "optuna==3.4.0",
    "joblib==1.3.2",
    "pandas==2.1.1",
    "scikit-learn==1.3.1",
    "xgboost==2.0.1",
    "lightgbm==4.1.0",
    "catboost==1.2.2",
    "scikit-optimize==0.9.0",
    "pyaml==23.9.7",
    "easydict==1.11",
    "llvmlite==0.41.1",
    "numba==0.58.1",
    "numpy==1.26.2",
    "shap==0.43.0",
    "slicer==0.0.7",
    "lazy_loader==0.3",
    "lime==0.2.0.1",
    "scikit-image==0.22.0",
    "tifffile==2023.9.26",
    "databricks-cli-0.18.0",
    "docker-6.1.3",
    "entrypoints-0.4",
    "mlflow-2.8.1",
    "pyarrow-14.0.1",
    "pyjwt-2.8.0",
    "querystring-parser-1.2.4",
    "sqlparse-0.4.4",
    "tabulate-0.9.0",
    "waitress-2.1.2",
    "websocket-client-1.6.4",
    "annotated-types-0.6.0",
    "anyio-3.7.1",
    "fastapi-0.104.1",
    "pydantic-2.5.1",
    "pydantic-core-2.14.3",
    "sniffio-1.3.0",
    "starlette-0.27.0",
    "typing-extensions-4.8.0",
]

if __name__ == "__main__":
    set_up(
        name="all you need is ml",
        description="all you need is ml",
        long_description=long_description,
        long_description_content_type="text/markdown",
        author="Minseong Kim",
        author_email="qtddpms@gmail.com",
        url="https://github.com/mskimS2/tabular-data",
        license="Apache 2.0",
        package_dir={"": "src"},
        packages=find_packages("src"),
        entry_points={},
        include_package_data=True,
        install_requires=INSTALL_REQUIRES,
        platforms=["linux", "unix"],
        python_requires=">=3.8",
    )