classifier:
    dataset:
        - train_data: ""
    # - https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html
    arguments:
        - model_name: "decision_tree"
        - task: "classification"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True
        - problem_type: "binary_classification"
        - device: "cpu"
        - only_one_train: True
        - output_path: "results"
        - criterion: "gini" # ["gini", "entropy", "log_loss"]
        - splitter: "best" # "best", "random"
        - max_depth: None
        - min_samples_split: 2
        - min_samples_leaf: 1
        - min_weight_fraction_leaf: 0.
        - max_leaf_nodes: None
        - min_impurity_decrease: 0.
        - class_weight: None # "balanced", "balanced_subsample"
        - ccp_alpha: 0.

regressor:
    dataset:
        - train_data: ""
    # https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor
    arguments:
        - model_name: "decision_tree"
        - task: "regression"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True # [True, False]
        - problem_type: "single_column_regression"
        - device: "cpu"
        - only_one_train: True # [True, False]
        - output_path: "results"
        - criterion: "gini" # ["gini", "entropy", "log_loss"]
        - splitter: "best" # "best", "random"
        - max_depth: None
        - min_samples_split: 2
        - min_samples_leaf: 1
        - min_weight_fraction_leaf: 0.
        - max_leaf_nodes: None
        - max_features: None # ["auto", "sqrt", "log2"]
        - min_impurity_decrease: 0.
        - class_weight: None # "balanced", "balanced_subsample"
        - ccp_alpha: 0.