classification:
    dataset:
        - train_data: "dataset/binary_classification.csv"
    
    # - https://lightgbm.readthedocs.io/en/stable/Parameters.html
    arguments:
        - model_name: "lightgbm"
        - task: "classification"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True
        - verbose: False
        - problem_type: "binary_classification"
        - device: "cpu"
        - only_one_train: True
        - output_path: "results"
        - num_iterations: 100
        - num_leaves: 31
        - learning_rate: 0.1
        - tree_learner: serial # ["serial", "feature", "data", "voting"]
        - num_threads: 0
        - deterministic: False # [True, False]
        - early_stopping_round: 50
        - force_col_wise: False # [True, False]
        - force_row_wise: False # [True, False]
        - histogram_pool_size: -1.
        - max_depth: -1
        - min_data_in_leaf: 20
        - min_sum_hessian_in_leaf: 1e-3
        - bagging_fraction: 1.
        - pos_bagging_fraction: 1.
        - neg_bagging_fraction: 1.
        - bagging_freq: 0
        - bagging_seed: 3
        - feature_fraction: 1.
        - feature_fraction_bynode: 1.
        - feature_fraction_seed: 2
        - extra_trees: False # [True, False]
        - first_metric_only: False # [True, False]
        - max_delta_step: 0.
        - lambda_l1: 0.
        - lambda_l2: 0.
        - linear_lambda: 0.
        - min_gain_to_split: 0.
        - drop_rate: 0.1
        - max_drop: 50
        - skip_drop: 0.5
        - xgboost_dart_mode: False # [True, False]
        - uniform_drop: False # [True, False]
        - drop_seed: 4
        - top_rate: 0.2
        - other_rate: 0.1
        - min_data_per_group: 100
        - max_cat_threshold: 32
        - cat_l2: 10.
        - cat_smooth: 10.
        - max_cat_to_onehot: 4
        - top_k: 20
        - monotone_constraints: None
        - monotone_constraints_method: basic # ["basic", "intermediate", "advanced"]
        - monotone_penalty: 0.
        - feature_contri: None
        - forcedsplits_filename: ""
        - interaction_constraints: ""
        - refit_decay_rate: 0.9
        - cegb_tradeoff: 1.
        - cegb_penalty_split: 0.
        - output_model: "LightGBM_model.txt"
        - saved_feature_importance_type: 0
        - path_smooth: 0
        - verbosity: -1
        - snapshot_freq: -1
        - use_quantized_grad: False # [True, False]
        - num_grad_quant_bins: 4
        - quant_train_renew_leaf: False # [True, False]
        - stochastic_rounding: False # [True, False]

regression:
    dataset:
        - train_data: ""
    
    # - https://lightgbm.readthedocs.io/en/stable/Parameters.html
    arguments:
        - model_name: "lightgbm"
        - task: "classification"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True
        - verbose: False
        - problem_type: "binary_classification"
        - device: "cpu"
        - only_one_train: True
        - output_path: "results"
        - num_iterations: 100
        - num_leaves: 31
        - learning_rate: 0.1
        - tree_learner: serial # ["serial", "feature", "data", "voting"]
        - num_threads: 0
        - deterministic: False # [True, False]
        - early_stopping_round: 50
        - force_col_wise: False # [True, False]
        - force_row_wise: False # [True, False]
        - histogram_pool_size: -1.
        - max_depth: -1
        - min_data_in_leaf: 20
        - min_sum_hessian_in_leaf: 1e-3
        - bagging_fraction: 1.
        - pos_bagging_fraction: 1.
        - neg_bagging_fraction: 1.
        - bagging_freq: 0
        - bagging_seed: 3
        - feature_fraction: 1.
        - feature_fraction_bynode: 1.
        - feature_fraction_seed: 2
        - extra_trees: False # [True, False]
        - first_metric_only: False # [True, False]
        - max_delta_step: 0.
        - lambda_l1: 0.
        - lambda_l2: 0.
        - linear_lambda: 0.
        - min_gain_to_split: 0.
        - drop_rate: 0.1
        - max_drop: 50
        - skip_drop: 0.5
        - xgboost_dart_mode: False # [True, False]
        - uniform_drop: False # [True, False]
        - drop_seed: 4
        - top_rate: 0.2
        - other_rate: 0.1
        - min_data_per_group: 100
        - max_cat_threshold: 32
        - cat_l2: 10.
        - cat_smooth: 10.
        - max_cat_to_onehot: 4
        - top_k: 20
        - monotone_constraints: None
        - monotone_constraints_method: basic # ["basic", "intermediate", "advanced"]
        - monotone_penalty: 0.
        - feature_contri: None
        - forcedsplits_filename: ""
        - interaction_constraints: ""
        - refit_decay_rate: 0.9
        - cegb_tradeoff: 1.
        - cegb_penalty_split: 0.
        - output_model: "LightGBM_model.txt"
        - saved_feature_importance_type: 0
        - path_smooth: 0
        - verbosity: -1
        - snapshot_freq: -1
        - use_quantized_grad: False # [True, False]
        - num_grad_quant_bins: 4
        - quant_train_renew_leaf: False # [True, False]
        - stochastic_rounding: False # [True, False]