classifier:
    dataset:
        - train_data: ""
    # - https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
    arguments:
        - model_name: "random_forest"
        - task: "classification"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True
        - problem_type: "binary_classification"
        - device: "cpu"
        - only_one_train: True
        - output_path: "results"
        - n_estimation: 100
        - max_depth: 7
        - min_samples_split: 2
        - min_samples_leaf: 1
        - min_weight_fraction_leaf: 0.
        - max_features: 1.
        - max_leaf_nodes: None
        - min_impurity_decrease: 0.
        - bootstrap: True
        - oob_score: False
        - n_jobs: None
        - verbose: 0
        - warm_start: False
        - ccp_alpha: 0.
        - max_samples: None

regressor:
    dataset:
        - train_data: ""
    # https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
    arguments:
        - model_name: "random_forest"
        - task: "regression"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True # [True, False]
        - problem_type: "single_column_regression"
        - device: "cpu"
        - only_one_train: True # [True, False]
        - output_path: "results"
        - n_estimation: 100
        - max_depth: 7
        - min_samples_split: 2
        - min_samples_leaf: 1
        - min_weight_fraction_leaf: 0.
        - max_features: 1.
        - max_leaf_nodes: None
        - min_impurity_decrease: 0.
        - bootstrap: True # [True, False]
        - oob_score: False # [True, False]
        - n_jobs: None
        - verbose: 0
        - warm_start: False # [True, False]
        - ccp_alpha: 0.
        - max_samples: None