classification:
    dataset:
        - train_data: "dataset/binary_classification.csv"
    
    # - https://xgboost.readthedocs.io/en/stable/parameter.html
    arguments:
        - model_name: "xgboost"
        - task: "classification"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True
        - verbose: False
        - problem_type: "binary_classification"
        - device: "cpu"
        - only_one_train: True
        - output_path: "results"
        - learning_rate: 0.3
        - gamma: 0.
        - max_depth: 6
        - max_child_weight: 1
        - early_stopping_rounds: 50
        - max_delta_step: 0
        - subsample: 1.
        - sampling_method: uniform
        - colsample_bytree: 1
        - reg_lambda: 1.
        - alpha: 0.
        - tree_method: auto
        - scale_pos_weight: 1.
        - grow_policy: depthwise
        - max_leaves: 0

regression:
    dataset:
        - train_data: ""
    
    # - https://catboost.ai/en/docs/references/training-parameters/
    arguments:
       - model_name: "xgboost"
        - task: "regression"
        - num_folds: 5
        - random_seed: 42
        - shuffle: True
        - verbose: False
        - problem_type: "single_column_regression"
        - device: "cpu"
        - only_one_train: True
        - output_path: "results"
        - learning_rate: 0.3
        - gamma: 0.
        - max_depth: 6
        - max_child_weight: 1
        - early_stopping_rounds: 50
        - max_delta_step: 0
        - subsample: 1.
        - sampling_method: uniform
        - colsample_bytree: 1
        - reg_lambda: 1.
        - alpha: 0.
        - tree_method: auto
        - scale_pos_weight: 1.
        - grow_policy: depthwise
        - max_leaves: 0